name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          date=$(date "+%Y-%m-%d")
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${date}-${ts}" 

    - name: Login to DockerHub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and publish container image with tag
      uses: docker/build-push-action@v2
      with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
                      gh05tsh/go-rest-api:${{ steps.prep.outputs.BUILD_ID }}
